### ISSUE TITLE
version key missing

### ISSUE THREAD

**Issue by mantaalex** [myxor/ha-bitstampnet#2]
i have seen a message in my HA:
No 'version' key in the manifest file for custom integration 'bitstampnet'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'bitstampnet'

**Comment by myxor** [comment]
Hey @mantaalex,
thanks for reporting this. 
I added that version key and published a new release.
It seems to work now again.

I will close this issue - feel free to comment if it is not working for you.
